//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_RACKET                      131
#define IDB_BITMAP1                     132
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_BITMAP3                     157
#define IDB_SCREAMR5                    157
#define IDB_KIRBY                       158
#define IDB_BITMAP5                     160
#define IDB_test1                       167
#define IDB_WALKL1                      168
#define IDB_WALKL2                      169
#define IDB_WALKL3                      170
#define IDB_WALKL4                      171
#define IDB_WALKL5                      172
#define IDB_WALKL6                      173
#define IDB_WALKL7                      174
#define IDB_WALKL8                      175
#define IDB_WALKL9                      176
#define IDB_BITMAP6                     177
#define IDB_WALKL10                     177
#define IDB_WALKR10                     178
#define IDB_CLOSE_EYES                  179
#define IDB_STAND                       180
#define IDB_WALKR1                      181
#define IDB_WALKR2                      182
#define IDB_WALKR3                      183
#define IDB_WALKR4                      184
#define IDB_WALKR5                      185
#define IDB_WALKR6                      186
#define IDB_WALKR7                      187
#define IDB_WALKR8                      188
#define IDB_WALKR9                      189
#define IDB_CLOSE_EYES_L                190
#define IDB_STANDL                      191
#define IDB_DOWNL2                      192
#define IDB_DOWNL1                      193
#define IDB_DOWNR2                      194
#define IDB_BITMAP9                     195
#define IDB_DOWNR1                      195
#define IDB_WALKL11                     196
#define IDB_BITMAP4                     197
#define IDB_FLYR1                       197
#define IDB_BITMAP7                     198
#define IDB_FLYR2                       198
#define IDB_BITMAP8                     199
#define IDB_FLYR3                       199
#define IDB_BITMAP10                    200
#define IDB_FLYR4                       200
#define IDB_BITMAP11                    201
#define IDB_FLYR5                       201
#define IDB_BITMAP12                    202
#define IDB_FLYR6                       202
#define IDB_JUMPR1                      203
#define IDB_JUMPR2                      204
#define IDB_JUMPR3                      205
#define IDB_JUMPR4                      206
#define IDB_JUMPR5                      207
#define IDB_JUMPR6                      208
#define IDB_JUMPR7                      209
#define IDB_JUMPR8                      210
#define IDB_JUMPR9                      211
#define IDB_JUMPR10                     212
#define IDB_BITMAP13                    213
#define IDB_JUMPL1                      213
#define IDB_SCREAML1                    214
#define IDB_SCREAML2                    215
#define IDB_SCREAML3                    216
#define IDB_SCREAML4                    217
#define IDB_SCREAML5                    218
#define IDB_SCREAMR1                    219
#define IDB_SCREAMR2                    220
#define IDB_SCREAMR3                    221
#define IDB_SCREAMR4                    222
#define IDB_BITMAP24                    235
#define IDB_BITMAP14                    236
#define IDB_STARBLOCK                   236
#define IDB_STAr                        238
#define IDB_STARTHROW                   238
#define IDB_DOOR                        239
#define IDB_STARTBACK                   241
#define IDB_BITMAP15                    242
#define IDB_SAVEBACK                    242
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        243
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
